### ISSUE TITLE
Rebase over main failing due to OOM persist dir missing

### ISSUE THREAD

**Issue by c3d** [c3d/podman#11]
After rebasing on today's main, there is a compilation error because a new method, `OOMFilePath` was added to the runtime interface.

```
libpod/oci_shimv2_common.go:147:9: cannot use runtime (variable of type *ShimV2OCIRuntime) as OCIRuntime value in return statement: *ShimV2OCIRuntime does not implement OCIRuntime (missing method OOMFilePath)

```

**Comment by c3d** [comment]
This was added as part of commit 667311c7d509794146114e05e7699bf3109bcee3, which is 11 months old but was apparently only merged recently

**Comment by c3d** [comment]
The calling code does not seem too ready to handle an error silently. However, it seems to be happy with a file that does not exist, so that's probably the safe thing to return.

``` go
func (c *Container) handleExitFile(exitFile string, fi os.FileInfo) error {
    ...
	oomFilePath, err := c.oomFilePath()
	if err != nil {
		return err
	}
	if _, err = os.Stat(oomFilePath); err == nil {
		c.state.OOMKilled = true
	}

	c.state.Exited = true
    ...
}
```
